@hostname = http://localhost:3000

GET {{hostname}}/api/sauces
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZjNzliYzVhNzQxYTc3ZWM5OGFkZWYiLCJpYXQiOjE2NjA3MTM0MDQsImV4cCI6MTY2MDc5OTgwNH0.GwLjp0bx8tIREhsuGc2KfJRBbfaE3M7ZLpj3nta_2xM

###

POST {{hostname}}/api/sauces
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmZjNzliYzVhNzQxYTc3ZWM5OGFkZWYiLCJpYXQiOjE2NjA3MTM0MDQsImV4cCI6MTY2MDc5OTgwNH0.GwLjp0bx8tIREhsuGc2KfJRBbfaE3M7ZLpj3nta_2xM

{
    "userId": "62fb6763693924a40b64b00c",
    "name": "pilipili1",
    "manufacturer": "mexicain",
    "description": "aie aie",
    "mainPepper": "piment",
    "imageUrl": ,
    "heat": 4,
    "likes": 0,
    "dislikes": 0,
    "usersLiked": [],
    "usersDisliked": []
}

###

POST {{hostname}}/api/auth/signup
content-type: application/json

{
    "email": "camille@gmail.com",
    "password": "camille" 
}